# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Junhua Yao <br> 姚俊华" # 从你的 index.html <title> 获取
description              : "Junhua Yao's personal academic homepage. Freshman exploring Computer Science, Generative AI, and Embodied AI ." # 根据你的 About Me 内容生成，你可以按需修改
repository               : "huashanjian/huashanjian.github.io" # 根据你的 GitHub 用户名 huashanjian 推断，请确保这是你的 Pages 仓库名 (通常是 用户名.github.io)
google_scholar_stats_use_cdn : true # 根据之前的说明保持 true
theme                    : minimal-mistakes-jekyll # <--- 添加这一行

# google analytics
google_analytics_id      :  # 如果你有 Google Analytics ID，请填写在这里

# SEO Related
google_site_verification :  # 如果有 Google Search Console 验证码，填这里
bing_site_verification   :  # 如果有 Bing Webmaster Tools 验证码，填这里
baidu_site_verification  :  # 如果有 百度资源平台 验证码，填这里

# Site Author (根据你的 index.html 内容填写)
author:
  name             : "Junhua Yao <br> 姚俊华" # 从你的 index.html <h1> 获取
  avatar           : "images/self.jpg" # 你的头像是 self.jpg，请确保它在项目的 images 文件夹下。如果不在，请修改路径或移动文件。
  bio              : "学术精神的本质恰恰是恢复人类的天真。<br>At its heart, the academic spirit is about recapturing a childlike sense of wonder." # 从你的 index.html <div class="motto"> 获取，你也可以换成其他简介
  location         : "Guangzhou, China" # 从你的 About Me 内容推断
  employer         : # 你是学生，可以留空或者填学校名称
  pubmed           : # 留空
  # !!! 重要：这里使用你之前提供的 Google Scholar ID !!!
  googlescholar    : "https://scholar.google.com/citations?user=UwMitgEAAAAJ"
  email            : "junhuayao41@gmail.com" # 从你的 index.html Contact 部分获取
  researchgate     :  # 留空
  uri              : # 留空
  bitbucket        : # 留空
  codepen          : # 留空
  dribbble         : # 留空
  flickr           : # 留空
  facebook         : # 留空
  foursquare       : # 留空
  github           : "huashanjian" # 从你的 index.html Contact/Profile 部分获取 (只填用户名)
  google_plus      : # 留空
  keybase          : # 留空
  instagram        : # 留空
  impactstory      : # 留空
  lastfm           : # 留空
  linkedin         : # 留空
  dblp             : # 留空
  orcid            : # 留空
  pinterest        : # 留空
  soundcloud       : # 留空
  stackoverflow    : # 留空
  steam            : # 留空
  tumblr           : # 留空
  twitter          : "Junhua_Yao13" # 从你的 index.html Contact/Profile 部分获取 (只填用户名)
  vine             : # 留空
  weibo            : # 留空
  xing             : # 留空
  youtube          : # 留空
  wikipedia        : # 留空


# Collections
collections:
  jottings:
    output: true
    permalink: /jottings/:path/

# Reading Files (以下保持默认配置，除非你知道要改什么)
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
